// src/components/modals/RenameFolderModal.tsx
import { createEffect, createRenderEffect, createSignal, on } from 'solid-js'
import { z } from 'zod'
import { Button } from '~/components/ui/button'
import {
	Dialog,
	DialogContent,
	DialogDescription,
	DialogFooter,
	DialogHeader,
	DialogTitle
} from '~/components/ui/dialog'
import { Input } from '~/components/ui/input'
import { Label } from '~/components/ui/label'
import { mutations } from '~/lib/db/utils'
import { useFilesystem } from '~/stores'
import { parseFormData, selectInputById } from '~/utils'

export const [renameFolderDialogOpen, setRenameFolderDialogOpen] = createSignal(false)

export function RenameFolderModal() {
	const [{ selectedFolder }, { refetchFilesAndFolders }] = useFilesystem()
	async function onSubmit(e: SubmitEvent) {
		e.preventDefault()
		try {
			const { name } = parseFormData(e.target as HTMLFormElement, z.object({ name: z.string() }))
			await mutations.renameFolder(selectedFolder()!.id, name)
			refetchFilesAndFolders()
		} finally {
			setRenameFolderDialogOpen(false)
		}
	}

	createRenderEffect(
		on(renameFolderDialogOpen, (open) => {
			if (!open) return
			if (!selectedFolder()) {
				setRenameFolderDialogOpen(false)
				console.error('No folder selected')
			}
		})
	)

	createEffect(
		on(renameFolderDialogOpen, (open) => {
			if (!open) return
			if (!selectedFolder()) return
			setTimeout(() => selectInputById('name'))
		})
	)

	return (
		<Dialog open={renameFolderDialogOpen()} onOpenChange={setRenameFolderDialogOpen}>
			<DialogContent class="sm:max-w-[425px]">
				<form onSubmit={onSubmit}>
					<DialogHeader>
						<DialogTitle>Rename Folder</DialogTitle>
						<DialogDescription>Rename a folder. Click rename when done.</DialogDescription>
					</DialogHeader>
					<div class="grid gap-4 py-4">
						<div class="grid grid-cols-4 items-center gap-4">
							<Label for="name" class="text-right">
								Name
							</Label>
							<Input name="name" id="name" value={selectedFolder()!.name} class="col-span-3" />
						</div>
					</div>
					<DialogFooter>
						<Button type="submit">Rename</Button>
					</DialogFooter>
				</form>
			</DialogContent>
		</Dialog>
	)
}

// apps/client/src/components/modals/RenameFolderModal.svelte
<script lang="ts" context="module">
	import { writable } from '@square/svelte-store';
	export const renameFolderModalOpen = writable(false);
</script>

<script lang="ts">
	import { z } from 'zod';
	import { Button } from '$/components/ui/button';
	import {
		Dialog,
		DialogContent,
		DialogDescription,
		DialogFooter,
		DialogHeader,
		DialogTitle
	} from '$/components/ui/dialog';
	import { Input } from '$/components/ui/input';
	import { Label } from '$/components/ui/label';
	import { parseFormData, selectInputById } from '$/utils';
	import { invalidate } from '$app/navigation';
	import { page } from '$app/stores';
	import { putNode } from 'db/queries/v1/nodes/by-id';
	import { useClipboard } from '$/stores/clipboard';
	import { getSQLocalClient } from '$/lib/db/sqlocal.client';

	const clipboard = useClipboard();
	$: node = $clipboard.nodes[0]!;

	$: pwd = decodeURI($page.url.pathname);
	async function onsubmit(e: SubmitEvent) {
		e.preventDefault();
		try {
			const { name } = parseFormData(e.target as HTMLFormElement, z.object({ name: z.string() }));
			const db = getSQLocalClient();
			await putNode(db, { node: { id: node.id, name } });
			await invalidate(`pwd:${pwd}`);
		} finally {
			$renameFolderModalOpen = false;
		}
	}
</script>

<Dialog
	bind:open={$renameFolderModalOpen}
	onOpenChange={() => {
		if (!open) return;
		if (!node) {
			$renameFolderModalOpen = false;
			console.error('No folder selected');
			return;
		}
		setTimeout(() => selectInputById('name'));
	}}
>
	<DialogContent class="sm:max-w-[425px]">
		<form on:submit={onsubmit}>
			<DialogHeader>
				<DialogTitle>Rename Folder</DialogTitle>
				<DialogDescription>Rename a folder. Click rename when done.</DialogDescription>
			</DialogHeader>
			<div class="grid gap-4 py-4">
				<div class="grid grid-cols-4 items-center gap-4">
					<Label for="name" class="text-right">Name</Label>
					<Input name="name" id="name" value={node.name} class="col-span-3" />
				</div>
			</div>
			<DialogFooter>
				<Button type="submit">Rename</Button>
			</DialogFooter>
		</form>
	</DialogContent>
</Dialog>
