// apps/client/src/components/Sidebar.svelte
<script lang="ts">
	import { Button } from '$/components/ui/button';
	import { useActions } from '$/stores/actions';
	import { cn } from '$/utils/ui';
	import { useTaskQueue } from '$/stores/task-queue';

	const { actions } = useActions();
	const { items } = useTaskQueue();
	interface $$Props {
		class?: string;
	}

	async function signout() {
		localStorage.removeItem('jwtToken');
		window.location.reload();
	}
</script>

<div class={cn('border-offset-background flex flex-col gap-8 border-r', $$props.class)}>
	<div class="border-offset-background flex flex-col gap-2">
		{#each $actions as action}
			<Button
				class="flex items-center justify-end gap-2 self-end text-xs font-bold uppercase tracking-wider"
				on:click={action.onclick}
				variant="ghost"
				type="button"
			>
				<span>{action.label}</span>
				<span class={cn(action.icon, 'shrink-0 text-base')}></span>
			</Button>
		{/each}
	</div>
	<span class="grow" />
	<ul class="flex justify-end">
		{#each $items as item}
			<li class="flex items-center gap-4">
				<span class="text-xs font-bold uppercase tracking-wider">
					{item.title}
				</span>
				<span class="i-mdi:loading animate-spin" />
			</li>
		{/each}
	</ul>
	<div class="border-offset-background flex flex-col gap-2">
		<Button
			class="flex items-center justify-end gap-2 self-end text-xs font-bold uppercase tracking-wider"
			on:click={signout}
			variant="ghost"
			type="button"
		>
			<span>Sign Out</span>
			<span class="i-carbon:logout shrink-0 text-base"></span>
		</Button>
	</div>
</div>

// src/components/Sidebar.tsx
import { For } from 'solid-js'
import { setAddFolderDialogOpen } from '~/components/modals/AddFolderModal'
import { setAddListDialogOpen } from '~/components/modals/AddListModal'
import { Button } from '~/components/ui/button'
import { cn } from '~/lib/utils'

type TButton = {
	label: string
	icon?: string
	onClick: () => void
}

const BUTTONS = [
	{
		label: 'Add Folder',
		icon: 'i-carbon:folder-add',
		onClick: () => {
			setAddFolderDialogOpen(true)
		}
	},
	{
		label: 'Add List',
		icon: 'i-carbon:document-add',
		onClick: () => {
			setAddListDialogOpen(true)
		}
	}
] satisfies TButton[]

export function Sidebar(props: { class?: string }) {
	return (
		<div class={cn('flex flex-col gap-2 border-r border-offset-background', props.class)}>
			<For each={BUTTONS}>
				{(button) => (
					<Button
						class="flex gap-2 items-center uppercase text-xs font-bold tracking-wider justify-end"
						onClick={button.onClick}
						variant="ghost"
						type="button"
					>
						<span>{button.label}</span>
						<span class={cn(button.icon, 'text-base')}></span>
					</Button>
				)}
			</For>
		</div>
	)
}
